[package]
name = "nitidus"
authors = ["Joshka"]
description = "A TUI email client"
repository = "https://github.com/joshka/nitidus"
license = "MIT"
documentation = "https://docs.rs/nitidus"
version = "0.1.4"
edition = "2021"

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
color-eyre = { version = "0.6.2", features = ["issue-url"] }
crossterm = "0.27.0"
directories = "5.0.1"
email-lib = "0.15.0"
figment = { version = "0.10.13", features = ["env", "toml"] }
himalaya = "0.9.0"
ratatui = "0.25.0"
serde = "1.0.195"
serde_with = "3.5.1"
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }
toml = "0.8.8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-error = "0.2.0"
tracing-log = "0.2.0"
tui-logger = { version = "0.10.0", default-features = false, features = ["tracing-support"] }

# email-lib = { git = "https://git.sr.ht/~soywod/pimalaya", default-features = false }
# mail-builder = "0.3.1"
# tokio-rustls = "0.25.0"
