[package]
name = "nitidus"
authors = ["Joshka"]
description = "A TUI email client"
repository = "https://github.com/joshka/nitidus"
license = "MIT"
documentation = "https://docs.rs/nitidus"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
color-eyre = "0.6.2"
crossterm = "0.27.0"
email-lib = "0.15.0"
himalaya = "0.9.0"
ratatui = "0.24.0"
serde = "1.0.193"
tokio = { version = "1.34.0", features = ["full"] }
toml = "0.8.8"
